environment:
  matrix:
    - nodejs_version: LTS
    - nodejs_version: STABLE

install:
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - ./build.cmd

cache:
  - node_modules -> package.json, package-lock.json

test: off
